version: '3'

services:
  web:
    build: ./web
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./wp-data:/var/www/html

  app:
    build: ./app
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./wp-data:/var/www/html

  db:
    image: mysql:5.7.19
    env_file: .env
    volumes:
      - ./db-data:/var/lib/mysql

  cli:
    image: wordpress:cli
    env_file: .env
    depends_on:
      - db
      - app
    volumes:
      - ./cli-scripts:/cli-scripts
      - ./wp-data:/var/www/html
