version: '3'

services:
  web:
    build: ./web
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - wp-data:/var/www/html
      - ./web/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build: ./app
    env_file: .env
    depends_on:
      - db
    volumes:
      - wp-data:/var/www/html

  db:
    image: mysql:5.7.19
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql

  editor:
    image: yash268925/neovim-php
    volumes:
      - wp-data:/home/www-data/wp

  cli:
    image: wordpress:cli
    env_file: .env
    depends_on:
      - app
      - db
    volumes:
      - wp-data:/var/www/html

volumes:
  db-data:
    driver_opts:
      type: none
      device: ./db-data
      o: bind
  wp-data:
    driver_opts:
      type: none
      device: ./wp-data
      o: bind

